In [1]:
import numpy as np

# 1. Create a 2D array (4 branches × 6 months)
transactions = np.array([
    [1200, 1500, 1600, 1700, 1800, 2000],
    [800, 950, 1000, 1100, 1200, 1300],
    [2000, 2100, 2200, 2300, 2400, 2500],
    [1000, 1050, 1100, 1200, 1300, 1350]
])

# 2. Total transactions per branch
total_per_branch = np.sum(transactions, axis=1)
print("Total transactions per branch:", total_per_branch)

# 3. Branch with the highest total
highest_branch = np.argmax(total_per_branch)
print("Branch with highest total transactions:", highest_branch + 1)

# 4. Average monthly transaction volume across all branches
avg_monthly = np.mean(transactions, axis=0)
print("Average monthly transaction volume:", avg_monthly)

# 5. Reshape to 3x8 and explain
reshaped = transactions.reshape(3, 8)
print("Reshaped array (3x8):\n", reshaped)
print("Implication: Reshaping changes how data is organized in memory without changing total elements. "
      "Here, 24 values are rearranged into 3 rows and 8 columns for analysis flexibility.")

Total transactions per branch: [ 9800  6350 13500  7000]
Branch with highest total transactions: 3
Average monthly transaction volume: [1250.  1400.  1475.  1575.  1675.  1787.5]
Reshaped array (3x8):
 [[1200 1500 1600 1700 1800 2000  800  950]
 [1000 1100 1200 1300 2000 2100 2200 2300]
 [2400 2500 1000 1050 1100 1200 1300 1350]]
Implication: Reshaping changes how data is organized in memory without changing total elements. Here, 24 values are rearranged into 3 rows and 8 columns for analysis flexibility.
